Cuisine.create([
  {  name: "Европейская"  },
  {  name: "Итальянская"  },
  {  name: "Азиатская"  },
  {  name: "Японская"  },
  {  name: "Китайская"  },
  {  name: "Кавказская"  },
  {  name: "Армянская"  },
  {  name: "Грузинская"  },
  {  name: "Узбекская"  },
  {  name: "Осетинская"  },
  {  name: "Индийская"  },
  {  name: "Русская Украинская"  },
  {  name: "Американская"  },
  {  name: "Авторская"  },
  {  name: "Пицца"  },
  {  name: "Суши"  },
  {  name: "Бургеры Сэндвичи"  },
  {  name: "Пироги"  },
  {  name: "Лапша"  },
  {  name: "Гриль Шашлыки"  },
  {  name: "Вегетарианские блюда"  },
  {  name: "Морепродукты"  },
  {  name: "Салаты"  },
  {  name: "Десерты"  },
  {  name: "Алкогольные напитки"  },
  {  name: "Закуски к пиву"  }
])

msk = City.create({  name: 'Москва'  })
spb = City.create({  name: 'Санкт-Петербург'  })

District.create([
  { name: "Авиамоторная", city: msk },
  { name: "Автозаводская", city: msk },
  { name: "Академическая", city: msk },
  { name: "Александровский сад", city: msk },
  { name: "Алексеевская", city: msk },
  { name: "Алма-Атинская", city: msk },
  { name: "Алтуфьево", city: msk },
  { name: "Аннино", city: msk },
  { name: "Арбатская", city: msk },
  { name: "Арбатская", city: msk },
  { name: "Арбатская площадь", city: msk },
  { name: "Аэропорт", city: msk },
  { name: "Бабушкинская", city: msk },
  { name: "Багратионовская", city: msk },
  { name: "Баррикадная", city: msk },
  { name: "Бауманская", city: msk },
  { name: "Беговая", city: msk },
  { name: "Беломорская", city: msk },
  { name: "Белорусская", city: msk },
  { name: "Беляево", city: msk },
  { name: "Бибирево", city: msk },
  { name: "Библиотека имени Ленина", city: msk },
  { name: "Битцевский парк", city: msk },
  { name: "Борисово", city: msk },
  { name: "Боровицкая", city: msk },
  { name: "Боровское шоссе", city: msk },
  { name: "Ботанический сад", city: msk },
  { name: "Братеево", city: msk },
  { name: "Братиславская", city: msk },
  { name: "Бульвар адмирала Ушакова", city: msk },
  { name: "Бульвар Дмитрия Донского", city: msk },
  { name: "Бунинская аллея", city: msk },
  { name: "Бутырский хутор", city: msk },
  { name: "Варшавская", city: msk },
  { name: "ВДНХ", city: msk },
  { name: "Вешняки", city: msk },
  { name: "Владыкино", city: msk },
  { name: "Водный стадион", city: msk },
  { name: "Воздвиженка", city: msk },
  { name: "Войковская", city: msk },
  { name: "Волгоградский проспект", city: msk },
  { name: "Волжская", city: msk },
  { name: "Волхонка", city: msk },
  { name: "Волоколамская:", city: msk },
  { name: "Волоколамская", city: msk },
  { name: "Воробьёвы горы", city: msk },
  { name: "ВСХВ", city: msk },
  { name: "Выставочная", city: msk },
  { name: "Выставочный центр", city: msk },
  { name: "Выхино", city: msk },
  { name: "Горьковская", city: msk },
  { name: "Городецкая", city: msk },
  { name: "Дворец Советов", city: msk },
  { name: "Деловой центр", city: msk },
  { name: "Дзержинская", city: msk },
  { name: "Динамо", city: msk },
  { name: "Дмитровская", city: msk },
  { name: "Добрынинская", city: msk },
  { name: "Домодедовская", city: msk },
  { name: "Дорогомиловская", city: msk },
  { name: "Достоевская", city: msk },
  { name: "Дубровка", city: msk },
  { name: "Евровокзал", city: msk },
  { name: "Ждановская", city: msk },
  { name: "Жулебино", city: msk },
  { name: "Завод имени Сталина", city: msk },
  { name: "Завод имени Лихачёва", city: msk },
  { name: "Зябликово", city: msk },
  { name: "Измайловская", city: msk },
  { name: "Измайловский парк", city: msk },
  { name: "Ильинские ворота", city: msk },
  { name: "Имени Коминтерна", city: msk },
  { name: "Имени Л. М. Кагановича", city: msk },
  { name: "Кадашевская", city: msk },
  { name: "Калининская", city: msk },
  { name: "Калужская", city: msk },
  { name: "Кантемировская", city: msk },
  { name: "Каховская", city: msk },
  { name: "Каширская", city: msk },
  { name: "Киевская", city: msk },
  { name: "Кировская", city: msk },
  { name: "Китай-город", city: msk },
  { name: "Климентовский переулок", city: msk },
  { name: "Кожуховская", city: msk },
  { name: "Коломенская", city: msk },
  { name: "Колхозная", city: msk },
  { name: "Коминтерн", city: msk },
  { name: "Комсомольская", city: msk },
  { name: "Коньково", city: msk },
  { name: "Конюшковская", city: msk },
  { name: "Красногвардейская", city: msk },
  { name: "Краснопресненская", city: msk },
  { name: "Красносельская", city: msk },
  { name: "Красные ворота", city: msk },
  { name: "Крестьянская застава", city: msk },
  { name: "Кропоткинская", city: msk },
  { name: "Крылатское", city: msk },
  { name: "Кузнецкий мост", city: msk },
  { name: "Кузьминки", city: msk },
  { name: "Кунцевская", city: msk },
  { name: "Курская", city: msk },
  { name: "Кутузовская", city: msk },
  { name: "Ленино", city: msk },
  { name: "Ленинские горы", city: msk },
  { name: "Ленинский проспект", city: msk },
  { name: "Лермонтовская", city: msk },
  { name: "Лесопарковая", city: msk },
  { name: "Лиазоново", city: msk },
  { name: "Лихоборы", city: msk },
  { name: "Ломоносовский проспект", city: msk },
  { name: "Лубянка", city: msk },
  { name: "Люблино", city: msk },
  { name: "Марксистская", city: msk },
  { name: "Маросейка", city: msk },
  { name: "Марьина Роща", city: msk },
  { name: "Марьино", city: msk },
  { name: "Маяковская", city: msk },
  { name: "Медведково", city: msk },
  { name: "Международная", city: msk },
  { name: "Менделеевская", city: msk },
  { name: "Мир", city: msk },
  { name: "Мироновская улица", city: msk },
  { name: "Митино", city: msk },
  { name: "Мичуринский проспект", city: msk },
  { name: "Молодёжная", city: msk },
  { name: "Москворецкая", city: msk },
  { name: "Мосфильмовская", city: msk },
  { name: "Мякинино", city: msk },
  { name: "Мясницкая", city: msk },
  { name: "Нагатинская", city: msk },
  { name: "Нагорная", city: msk },
  { name: "Нахимовский проспект", city: msk },
  { name: "Никулинская", city: msk },
  { name: "Ново-Алексеевская", city: msk },
  { name: "Новогиреево", city: msk },
  { name: "Новокосино", city: msk },
  { name: "Новокузнецкая", city: msk },
  { name: "Новокурьяново", city: msk },
  { name: "Новопеределкино", city: msk },
  { name: "Новослободская", city: msk },
  { name: "Новоясеневская", city: msk },
  { name: "Новые Черёмушки", city: msk },
  { name: "Окружная", city: msk },
  { name: "Октябрьская", city: msk },
  { name: "Октябрьское Поле", city: msk },
  { name: "Олимпийская деревня", city: msk },
  { name: "Орехово", city: msk },
  { name: "Останкино", city: msk },
  { name: "Остоженка", city: msk },
  { name: "Отрадное", city: msk },
  { name: "Охотный ряд", city: msk },
  { name: "Павелецкая", city: msk },
  { name: "Парк культуры", city: msk },
  { name: "Парк Победы", city: msk },
  { name: "Парк Победы-2", city: msk },
  { name: "Партизанская", city: msk },
  { name: "Первомайская", city: msk },
  { name: "Перово", city: msk },
  { name: "Петровско-Разумовская", city: msk },
  { name: "Печатники", city: msk },
  { name: "Печатники-2", city: msk },
  { name: "Пионерская", city: msk },
  { name: "Планерная", city: msk },
  { name: "Площадь Гагарина", city: msk },
  { name: "Площадь Ильича", city: msk },
  { name: "Площадь Ногина", city: msk },
  { name: "Площадь Революции", city: msk },
  { name: "Площадь Свердлова", city: msk },
  { name: "Площадь Свободы", city: msk },
  { name: "Площадь Суворова", city: msk },
  { name: "Покровские ворота", city: msk },
  { name: "Полежаевская", city: msk },
  { name: "Полянка", city: msk },
  { name: "Полянка-2", city: msk },
  { name: "Пражская", city: msk },
  { name: "Преображенская площадь", city: msk },
  { name: "Пролетарская", city: msk },
  { name: "Пронская", city: msk },
  { name: "Проспект Вернадского", city: msk },
  { name: "Проспект Маркса", city: msk },
  { name: "Проспект Мира", city: msk },
  { name: "Профсоюзная", city: msk },
  { name: "Пушкинская", city: msk },
  { name: "Пятницкое шоссе", city: msk },
  { name: "Речной вокзал", city: msk },
  { name: "Рижская", city: msk },
  { name: "Римская", city: msk },
  { name: "Рождествено", city: msk },
  { name: "Российская", city: msk },
  { name: "Рязанский проспект", city: msk },
  { name: "Савёловская", city: msk },
  { name: "Свиблово", city: msk },
  { name: "Севастопольская", city: msk },
  { name: "Селигерская", city: msk },
  { name: "Семёновская", city: msk },
  { name: "Серпуховская", city: msk },
  { name: "Славянский бульвар", city: msk },
  { name: "Смоленская", city: msk },
  { name: "Смоленская-2", city: msk },
  { name: "Смоленская-3", city: msk },
  { name: "Советская", city: msk },
  { name: "Сокол", city: msk },
  { name: "Сокольники", city: msk },
  { name: "Солнцево", city: msk },
  { name: "Спартаковская", city: msk },
  { name: "Спортивная", city: msk },
  { name: "Сретенский бульвар", city: msk },
  { name: "Стадион Динамо", city: msk },
  { name: "Стадион народов", city: msk },
  { name: "Стадион имени Сталина", city: msk },
  { name: "Стадион «Спартак»", city: msk },
  { name: "Сталинская", city: msk },
  { name: "Строгино", city: msk },
  { name: "Студенческая", city: msk },
  { name: "Сухаревская", city: msk },
  { name: "Сходненская", city: msk },
  { name: "Таганская", city: msk },
  { name: "Тверская", city: msk },
  { name: "Театральная", city: msk },
  { name: "Текстильщики", city: msk },
  { name: "Телецентр", city: msk },
  { name: "Терёшково", city: msk },
  { name: "Техавтоцентр", city: msk },
  { name: "Технопарк", city: msk },
  { name: "Тёплый Стан", city: msk },
  { name: "Тимирязевская", city: msk },
  { name: "Тимирязевская", city: msk },
  { name: "Третьяковская", city: msk },
  { name: "Триумфальная площадь", city: msk },
  { name: "Троице-Лыково", city: msk },
  { name: "Тропарево", city: msk },
  { name: "Трубная", city: msk },
  { name: "Тульская", city: msk },
  { name: "Тургеневская", city: msk },
  { name: "Тушинская", city: msk },
  { name: "Улица 1905 года", city: msk },
  { name: "Улица Коминтерна", city: msk },
  { name: "Улица Академика Королёва", city: msk },
  { name: "Улица Академика Янгеля", city: msk },
  { name: "Улица Горчакова", city: msk },
  { name: "Улица Дыбенко", city: msk },
  { name: "Улица Милашенкова", city: msk },
  { name: "Улица Остафьевская", city: msk },
  { name: "Улица Подбельского", city: msk },
  { name: "Улица Сергея Эйзенштейна", city: msk },
  { name: "Улица Скобелевская", city: msk },
  { name: "Улица Старокачаловская", city: msk },
  { name: "Улица Старопотаповская", city: msk },
  { name: "Ульяновская (Золоторожская)", city: msk },
  { name: "Университет", city: msk },
  { name: "Филёвский парк", city: msk },
  { name: "Фили", city: msk },
  { name: "Фрунзенская", city: msk },
  { name: "Ходынское поле", city: msk },
  { name: "Хорошёвская", city: msk },
  { name: "Царицыно", city: msk },
  { name: "Цветной бульвар", city: msk },
  { name: "Челобитьево", city: msk },
  { name: "Черкизовская", city: msk },
  { name: "Черкизовская-2", city: msk },
  { name: "Чертановская", city: msk },
  { name: "Чеховская", city: msk },
  { name: "Чистые пруды", city: msk },
  { name: "Чкаловская", city: msk },
  { name: "Шаболовская", city: msk },
  { name: "Шереметьевская", city: msk },
  { name: "Шипиловская", city: msk },
  { name: "Шоссе Энтузиастов", city: msk },
  { name: "Щёлковская", city: msk },
  { name: "Щёлковская-2", city: msk },
  { name: "Щербаковская", city: msk },
  { name: "Щукинская", city: msk },
  { name: "Электрозаводская", city: msk },
  { name: "Юбилейная", city: msk },
  { name: "Юго-Западная", city: msk },
  { name: "Юго-Западная-2", city: msk },
  { name: "Южная", city: msk },
  { name: "Якиманка", city: msk },
  { name: "Ясенево", city: msk },
  { name: "Девяткино", city: spb },
  { name: "Гражданский проспект", city: spb },
  { name: "Академическая", city: spb },
  { name: "Политехническая", city: spb },
  { name: "Площадь Мужества", city: spb },
  { name: "Лесная", city: spb },
  { name: "Выборгская", city: spb },
  { name: "Площадь Ленина", city: spb },
  { name: "Чернышевская", city: spb },
  { name: "Площадь Восстания", city: spb },
  { name: "Владимирская", city: spb },
  { name: "Пушкинская", city: spb },
  { name: "Технологический институт", city: spb },
  { name: "Балтийская", city: spb },
  { name: "Нарвская", city: spb },
  { name: "Кировский завод", city: spb },
  { name: "Автово", city: spb },
  { name: "Ленинский проспект", city: spb },
  { name: "Проспект Ветеранов", city: spb },
  { name: "Парнас", city: spb },
  { name: "Проспект Просвещения", city: spb },
  { name: "Озерки", city: spb },
  { name: "Удельная", city: spb },
  { name: "Пионерская", city: spb },
  { name: "Чёрная речка", city: spb },
  { name: "Петроградская", city: spb },
  { name: "Горьковская", city: spb },
  { name: "Невский проспект", city: spb },
  { name: "Сенная площадь", city: spb },
  { name: "Технологический институт", city: spb },
  { name: "Фрунзенская", city: spb },
  { name: "Московские ворота", city: spb },
  { name: "Электросила", city: spb },
  { name: "Парк Победы", city: spb },
  { name: "Московская", city: spb },
  { name: "Звёздная", city: spb },
  { name: "Купчино", city: spb },
  { name: "Приморская", city: spb },
  { name: "Василеостровская", city: spb },
  { name: "Гостиный двор", city: spb },
  { name: "Маяковская", city: spb },
  { name: "Площадь Александра Невского-1", city: spb },
  { name: "Елизаровская", city: spb },
  { name: "Ломоносовская", city: spb },
  { name: "Пролетарская", city: spb },
  { name: "Обухово", city: spb },
  { name: "Рыбацкое", city: spb },
  { name: "Спасская", city: spb },
  { name: "Достоевская", city: spb },
  { name: "Лиговский проспект", city: spb },
  { name: "Площадь Александра Невского-2", city: spb },
  { name: "Новочеркасская", city: spb },
  { name: "Ладожская", city: spb },
  { name: "Проспект Большевиков", city: spb },
  { name: "Улица Дыбенко", city: spb },
  { name: "Комендантский проспект", city: spb },
  { name: "Старая Деревня", city: spb },
  { name: "Крестовский остров", city: spb },
  { name: "Чкаловская", city: spb },
  { name: "Спортивная", city: spb },
  { name: "Садовая", city: spb },
  { name: "Звенигородская", city: spb },
  { name: "Волковская", city: spb }
])